export const CITY_SELECTED = 'CITY_SELECTED';
export const WEATHER_LOADING = 'WEATHER_LOADING';
export const WEATHER_LOADED = 'WEATHER_LOADED';
export const WEATHER_LOAD_FAILED = 'WEATHER_LOAD_FAILED';
